import { Country, Operator, SimPlan, User } from './types';

export const INITIAL_COUNTRIES: Country[] = [
  { id: 'af', name_es: 'Afganistán', name_en: 'Afghanistan', continent: 'Asia', currency: 'AFN', flag: '🇦🇫' },
  { id: 'al', name_es: 'Albania', name_en: 'Albania', continent: 'Europe', currency: 'ALL', flag: '🇦🇱' },
  { id: 'dz', name_es: 'Argelia', name_en: 'Algeria', continent: 'Africa', currency: 'DZD', flag: '🇩🇿' },
  { id: 'ad', name_es: 'Andorra', name_en: 'Andorra', continent: 'Europe', currency: 'EUR', flag: '🇦🇩' },
  { id: 'ao', name_es: 'Angola', name_en: 'Angola', continent: 'Africa', currency: 'AOA', flag: '🇦🇴' },
  { id: 'ag', name_es: 'Antigua y Barbuda', name_en: 'Antigua and Barbuda', continent: 'North America', currency: 'XCD', flag: '🇦🇬' },
  { id: 'ar', name_es: 'Argentina', name_en: 'Argentina', continent: 'South America', currency: 'ARS', flag: '🇦🇷' },
  { id: 'am', name_es: 'Armenia', name_en: 'Armenia', continent: 'Asia', currency: 'AMD', flag: '🇦🇲' },
  { id: 'au', name_es: 'Australia', name_en: 'Australia', continent: 'Oceania', currency: 'AUD', flag: '🇦🇺' },
  { id: 'at', name_es: 'Austria', name_en: 'Austria', continent: 'Europe', currency: 'EUR', flag: '🇦🇹' },
  { id: 'az', name_es: 'Azerbaiyán', name_en: 'Azerbaijan', continent: 'Asia', currency: 'AZN', flag: '🇦🇿' },
  { id: 'bs', name_es: 'Bahamas', name_en: 'Bahamas', continent: 'North America', currency: 'BSD', flag: '🇧🇸' },
  { id: 'bh', name_es: 'Baréin', name_en: 'Bahrain', continent: 'Asia', currency: 'BHD', flag: '🇧🇭' },
  { id: 'bd', name_es: 'Bangladés', name_en: 'Bangladesh', continent: 'Asia', currency: 'BDT', flag: '🇧🇩' },
  { id: 'bb', name_es: 'Barbados', name_en: 'Barbados', continent: 'North America', currency: 'BBD', flag: '🇧🇧' },
  { id: 'by', name_es: 'Bielorrusia', name_en: 'Belarus', continent: 'Europe', currency: 'BYN', flag: '🇧🇾' },
  { id: 'be', name_es: 'Bélgica', name_en: 'Belgium', continent: 'Europe', currency: 'EUR', flag: '🇧🇪' },
  { id: 'bz', name_es: 'Belice', name_en: 'Belize', continent: 'North America', currency: 'BZD', flag: '🇧🇿' },
  { id: 'bj', name_es: 'Benín', name_en: 'Benin', continent: 'Africa', currency: 'XOF', flag: '🇧🇯' },
  { id: 'bt', name_es: 'Bután', name_en: 'Bhutan', continent: 'Asia', currency: 'BTN', flag: '🇧🇹' },
  { id: 'bo', name_es: 'Bolivia', name_en: 'Bolivia', continent: 'South America', currency: 'BOB', flag: '🇧🇴' },
  { id: 'ba', name_es: 'Bosnia y Herzegovina', name_en: 'Bosnia and Herzegovina', continent: 'Europe', currency: 'BAM', flag: '🇧🇦' },
  { id: 'bw', name_es: 'Botsuana', name_en: 'Botswana', continent: 'Africa', currency: 'BWP', flag: '🇧🇼' },
  { id: 'br', name_es: 'Brasil', name_en: 'Brazil', continent: 'South America', currency: 'BRL', flag: '🇧🇷' },
  { id: 'bn', name_es: 'Brunéi', name_en: 'Brunei', continent: 'Asia', currency: 'BND', flag: '🇧🇳' },
  { id: 'bg', name_es: 'Bulgaria', name_en: 'Bulgaria', continent: 'Europe', currency: 'BGN', flag: '🇧🇬' },
  { id: 'bf', name_es: 'Burkina Faso', name_en: 'Burkina Faso', continent: 'Africa', currency: 'XOF', flag: '🇧🇫' },
  { id: 'bi', name_es: 'Burundi', name_en: 'Burundi', continent: 'Africa', currency: 'BIF', flag: '🇧🇮' },
  { id: 'cv', name_es: 'Cabo Verde', name_en: 'Cabo Verde', continent: 'Africa', currency: 'CVE', flag: '🇨🇻' },
  { id: 'kh', name_es: 'Camboya', name_en: 'Cambodia', continent: 'Asia', currency: 'KHR', flag: '🇰🇭' },
  { id: 'cm', name_es: 'Camerún', name_en: 'Cameroon', continent: 'Africa', currency: 'XAF', flag: '🇨🇲' },
  { id: 'ca', name_es: 'Canadá', name_en: 'Canada', continent: 'North America', currency: 'CAD', flag: '🇨🇦' },
  { id: 'cf', name_es: 'República Centroafricana', name_en: 'Central African Republic', continent: 'Africa', currency: 'XAF', flag: '🇨🇫' },
  { id: 'td', name_es: 'Chad', name_en: 'Chad', continent: 'Africa', currency: 'XAF', flag: '🇹🇩' },
  { id: 'cl', name_es: 'Chile', name_en: 'Chile', continent: 'South America', currency: 'CLP', flag: '🇨🇱' },
  { id: 'cn', name_es: 'China', name_en: 'China', continent: 'Asia', currency: 'CNY', flag: '🇨🇳' },
  { id: 'co', name_es: 'Colombia', name_en: 'Colombia', continent: 'South America', currency: 'COP', flag: '🇨🇴' },
  { id: 'km', name_es: 'Comoras', name_en: 'Comoros', continent: 'Africa', currency: 'KMF', flag: '🇰🇲' },
  { id: 'cd', name_es: 'Congo (RDC)', name_en: 'Congo (DRC)', continent: 'Africa', currency: 'CDF', flag: '🇨🇩' },
  { id: 'cg', name_es: 'Congo', name_en: 'Congo', continent: 'Africa', currency: 'XAF', flag: '🇨🇬' },
  { id: 'cr', name_es: 'Costa Rica', name_en: 'Costa Rica', continent: 'North America', currency: 'CRC', flag: '🇨🇷' },
  { id: 'hr', name_es: 'Croacia', name_en: 'Croatia', continent: 'Europe', currency: 'EUR', flag: '🇭🇷' },
  { id: 'cu', name_es: 'Cuba', name_en: 'Cuba', continent: 'North America', currency: 'CUP', flag: '🇨🇺' },
  { id: 'cy', name_es: 'Chipre', name_en: 'Cyprus', continent: 'Europe', currency: 'EUR', flag: '🇨🇾' },
  { id: 'cz', name_es: 'República Checa', name_en: 'Czech Republic', continent: 'Europe', currency: 'CZK', flag: '🇨🇿' },
  { id: 'dk', name_es: 'Dinamarca', name_en: 'Denmark', continent: 'Europe', currency: 'DKK', flag: '🇩🇰' },
  { id: 'dj', name_es: 'Yibuti', name_en: 'Djibouti', continent: 'Africa', currency: 'DJF', flag: '🇩🇯' },
  { id: 'dm', name_es: 'Dominica', name_en: 'Dominica', continent: 'North America', currency: 'XCD', flag: '🇩🇲' },
  { id: 'do', name_es: 'República Dominicana', name_en: 'Dominican Republic', continent: 'North America', currency: 'DOP', flag: '🇩🇴' },
  { id: 'tl', name_es: 'Timor Oriental', name_en: 'East Timor', continent: 'Asia', currency: 'USD', flag: '🇹🇱' },
  { id: 'ec', name_es: 'Ecuador', name_en: 'Ecuador', continent: 'South America', currency: 'USD', flag: '🇪🇨' },
  { id: 'eg', name_es: 'Egipto', name_en: 'Egypt', continent: 'Africa', currency: 'EGP', flag: '🇪🇬' },
  { id: 'sv', name_es: 'El Salvador', name_en: 'El Salvador', continent: 'North America', currency: 'USD', flag: '🇸🇻' },
  { id: 'gq', name_es: 'Guinea Ecuatorial', name_en: 'Equatorial Guinea', continent: 'Africa', currency: 'XAF', flag: '🇬🇶' },
  { id: 'er', name_es: 'Eritrea', name_en: 'Eritrea', continent: 'Africa', currency: 'ERN', flag: '🇪🇷' },
  { id: 'ee', name_es: 'Estonia', name_en: 'Estonia', continent: 'Europe', currency: 'EUR', flag: '🇪🇪' },
  { id: 'sz', name_es: 'Esuatini', name_en: 'Eswatini', continent: 'Africa', currency: 'SZL', flag: '🇸🇿' },
  { id: 'et', name_es: 'Etiopía', name_en: 'Ethiopia', continent: 'Africa', currency: 'ETB', flag: '🇪🇹' },
  { id: 'fj', name_es: 'Fiyi', name_en: 'Fiji', continent: 'Oceania', currency: 'FJD', flag: '🇫🇯' },
  { id: 'fi', name_es: 'Finlandia', name_en: 'Finland', continent: 'Europe', currency: 'EUR', flag: '🇫🇮' },
  { id: 'fr', name_es: 'Francia', name_en: 'France', continent: 'Europe', currency: 'EUR', flag: '🇫🇷' },
  { id: 'ga', name_es: 'Gabón', name_en: 'Gabon', continent: 'Africa', currency: 'XAF', flag: '🇬🇦' },
  { id: 'gm', name_es: 'Gambia', name_en: 'Gambia', continent: 'Africa', currency: 'GMD', flag: '🇬🇲' },
  { id: 'ge', name_es: 'Georgia', name_en: 'Georgia', continent: 'Asia', currency: 'GEL', flag: '🇬🇪' },
  { id: 'de', name_es: 'Alemania', name_en: 'Germany', continent: 'Europe', currency: 'EUR', flag: '🇩🇪' },
  { id: 'gh', name_es: 'Ghana', name_en: 'Ghana', continent: 'Africa', currency: 'GHS', flag: '🇬🇭' },
  { id: 'gr', name_es: 'Grecia', name_en: 'Greece', continent: 'Europe', currency: 'EUR', flag: '🇬🇷' },
  { id: 'gd', name_es: 'Granada', name_en: 'Grenada', continent: 'North America', currency: 'XCD', flag: '🇬🇩' },
  { id: 'gt', name_es: 'Guatemala', name_en: 'Guatemala', continent: 'North America', currency: 'GTQ', flag: '🇬🇹' },
  { id: 'gn', name_es: 'Guinea', name_en: 'Guinea', continent: 'Africa', currency: 'GNF', flag: '🇬🇳' },
  { id: 'gw', name_es: 'Guinea-Bisáu', name_en: 'Guinea-Bissau', continent: 'Africa', currency: 'XOF', flag: '🇬🇼' },
  { id: 'gy', name_es: 'Guyana', name_en: 'Guyana', continent: 'South America', currency: 'GYD', flag: '🇬🇾' },
  { id: 'ht', name_es: 'Haití', name_en: 'Haiti', continent: 'North America', currency: 'HTG', flag: '🇭🇹' },
  { id: 'hn', name_es: 'Honduras', name_en: 'Honduras', continent: 'North America', currency: 'HNL', flag: '🇭🇳' },
  { id: 'hu', name_es: 'Hungría', name_en: 'Hungary', continent: 'Europe', currency: 'HUF', flag: '🇭🇺' },
  { id: 'is', name_es: 'Islandia', name_en: 'Iceland', continent: 'Europe', currency: 'ISK', flag: '🇮🇸' },
  { id: 'in', name_es: 'India', name_en: 'India', continent: 'Asia', currency: 'INR', flag: '🇮🇳' },
  { id: 'id', name_es: 'Indonesia', name_en: 'Indonesia', continent: 'Asia', currency: 'IDR', flag: '🇮🇩' },
  { id: 'ir', name_es: 'Irán', name_en: 'Iran', continent: 'Asia', currency: 'IRR', flag: '🇮🇷' },
  { id: 'iq', name_es: 'Irak', name_en: 'Iraq', continent: 'Asia', currency: 'IQD', flag: '🇮🇶' },
  { id: 'ie', name_es: 'Irlanda', name_en: 'Ireland', continent: 'Europe', currency: 'EUR', flag: '🇮🇪' },
  { id: 'il', name_es: 'Israel', name_en: 'Israel', continent: 'Asia', currency: 'ILS', flag: '🇮🇱' },
  { id: 'it', name_es: 'Italia', name_en: 'Italy', continent: 'Europe', currency: 'EUR', flag: '🇮🇹' },
  { id: 'ci', name_es: 'Costa de Marfil', name_en: 'Ivory Coast', continent: 'Africa', currency: 'XOF', flag: '🇨🇮' },
  { id: 'jm', name_es: 'Jamaica', name_en: 'Jamaica', continent: 'North America', currency: 'JMD', flag: '🇯🇲' },
  { id: 'jp', name_es: 'Japón', name_en: 'Japan', continent: 'Asia', currency: 'JPY', flag: '🇯🇵' },
  { id: 'jo', name_es: 'Jordania', name_en: 'Jordan', continent: 'Asia', currency: 'JOD', flag: '🇯🇴' },
  { id: 'kz', name_es: 'Kazajistán', name_en: 'Kazakhstan', continent: 'Asia', currency: 'KZT', flag: '🇰🇿' },
  { id: 'ke', name_es: 'Kenia', name_en: 'Kenya', continent: 'Africa', currency: 'KES', flag: '🇰🇪' },
  { id: 'ki', name_es: 'Kiribati', name_en: 'Kiribati', continent: 'Oceania', currency: 'AUD', flag: '🇰🇮' },
  { id: 'kp', name_es: 'Corea del Norte', name_en: 'Korea (North)', continent: 'Asia', currency: 'KPW', flag: '🇰🇵' },
  { id: 'kr', name_es: 'Corea del Sur', name_en: 'Korea (South)', continent: 'Asia', currency: 'KRW', flag: '🇰🇷' },
  { id: 'xk', name_es: 'Kosovo', name_en: 'Kosovo', continent: 'Europe', currency: 'EUR', flag: '🇽🇰' },
  { id: 'kw', name_es: 'Kuwait', name_en: 'Kuwait', continent: 'Asia', currency: 'KWD', flag: '🇰🇼' },
  { id: 'kg', name_es: 'Kirguistán', name_en: 'Kyrgyzstan', continent: 'Asia', currency: 'KGS', flag: '🇰🇬' },
  { id: 'la', name_es: 'Laos', name_en: 'Laos', continent: 'Asia', currency: 'LAK', flag: '🇱🇦' },
  { id: 'lv', name_es: 'Letonia', name_en: 'Latvia', continent: 'Europe', currency: 'EUR', flag: '🇱🇻' },
  { id: 'lb', name_es: 'Líbano', name_en: 'Lebanon', continent: 'Asia', currency: 'LBP', flag: '🇱🇧' },
  { id: 'ls', name_es: 'Lesoto', name_en: 'Lesotho', continent: 'Africa', currency: 'LSL', flag: '🇱🇸' },
  { id: 'lr', name_es: 'Liberia', name_en: 'Liberia', continent: 'Africa', currency: 'LRD', flag: '🇱🇷' },
  { id: 'ly', name_es: 'Libia', name_en: 'Libya', continent: 'Africa', currency: 'LYD', flag: '🇱🇾' },
  { id: 'li', name_es: 'Liechtenstein', name_en: 'Liechtenstein', continent: 'Europe', currency: 'CHF', flag: '🇱🇮' },
  { id: 'lt', name_es: 'Lituania', name_en: 'Lithuania', continent: 'Europe', currency: 'EUR', flag: '🇱🇹' },
  { id: 'lu', name_es: 'Luxemburgo', name_en: 'Luxembourg', continent: 'Europe', currency: 'EUR', flag: '🇱🇺' },
  { id: 'mg', name_es: 'Madagascar', name_en: 'Madagascar', continent: 'Africa', currency: 'MGA', flag: '🇲🇬' },
  { id: 'mw', name_es: 'Malaui', name_en: 'Malawi', continent: 'Africa', currency: 'MWK', flag: '🇲🇼' },
  { id: 'my', name_es: 'Malasia', name_en: 'Malaysia', continent: 'Asia', currency: 'MYR', flag: '🇲🇾' },
  { id: 'mv', name_es: 'Maldivas', name_en: 'Maldives', continent: 'Asia', currency: 'MVR', flag: '🇲🇻' },
  { id: 'ml', name_es: 'Malí', name_en: 'Mali', continent: 'Africa', currency: 'XOF', flag: '🇲🇱' },
  { id: 'mt', name_es: 'Malta', name_en: 'Malta', continent: 'Europe', currency: 'EUR', flag: '🇲🇹' },
  { id: 'mh', name_es: 'Islas Marshall', name_en: 'Marshall Islands', continent: 'Oceania', currency: 'USD', flag: '🇲🇭' },
  { id: 'mr', name_es: 'Mauritania', name_en: 'Mauritania', continent: 'Africa', currency: 'MRU', flag: '🇲🇷' },
  { id: 'mu', name_es: 'Mauricio', name_en: 'Mauritius', continent: 'Africa', currency: 'MUR', flag: '🇲🇺' },
  { id: 'mx', name_es: 'México', name_en: 'Mexico', continent: 'North America', currency: 'MXN', flag: '🇲🇽' },
  { id: 'fm', name_es: 'Micronesia', name_en: 'Micronesia', continent: 'Oceania', currency: 'USD', flag: '🇫🇯' },
  { id: 'md', name_es: 'Moldavia', name_en: 'Moldova', continent: 'Europe', currency: 'MDL', flag: '🇲🇩' },
  { id: 'mc', name_es: 'Mónaco', name_en: 'Monaco', continent: 'Europe', currency: 'EUR', flag: '🇲🇨' },
  { id: 'mn', name_es: 'Mongolia', name_en: 'Mongolia', continent: 'Asia', currency: 'MNT', flag: '🇲🇳' },
  { id: 'me', name_es: 'Montenegro', name_en: 'Montenegro', continent: 'Europe', currency: 'EUR', flag: '🇲🇪' },
  { id: 'ma', name_es: 'Marruecos', name_en: 'Morocco', continent: 'Africa', currency: 'MAD', flag: '🇲🇦' },
  { id: 'mz', name_es: 'Mozambique', name_en: 'Mozambique', continent: 'Africa', currency: 'MZN', flag: '🇲🇿' },
  { id: 'mm', name_es: 'Myanmar', name_en: 'Myanmar', continent: 'Asia', currency: 'MMK', flag: '🇲🇲' },
  { id: 'na', name_es: 'Namibia', name_en: 'Namibia', continent: 'Africa', currency: 'NAD', flag: '🇳🇦' },
  { id: 'nr', name_es: 'Nauru', name_en: 'Nauru', continent: 'Oceania', currency: 'AUD', flag: '🇳🇷' },
  { id: 'np', name_es: 'Nepal', name_en: 'Nepal', continent: 'Asia', currency: 'NPR', flag: '🇳🇵' },
  { id: 'nl', name_es: 'Países Bajos', name_en: 'Netherlands', continent: 'Europe', currency: 'EUR', flag: '🇳🇱' },
  { id: 'nz', name_es: 'Nueva Zelanda', name_en: 'New Zealand', continent: 'Oceania', currency: 'NZD', flag: '🇳🇿' },
  { id: 'ni', name_es: 'Nicaragua', name_en: 'Nicaragua', continent: 'North America', currency: 'NIO', flag: '🇳🇮' },
  { id: 'ne', name_es: 'Níger', name_en: 'Niger', continent: 'Africa', currency: 'XOF', flag: '🇳🇪' },
  { id: 'ng', name_es: 'Nigeria', name_en: 'Nigeria', continent: 'Africa', currency: 'NGN', flag: '🇳🇬' },
  { id: 'mk', name_es: 'Macedonia del Norte', name_en: 'North Macedonia', continent: 'Europe', currency: 'MKD', flag: '🇲🇰' },
  { id: 'no', name_es: 'Noruega', name_en: 'Norway', continent: 'Europe', currency: 'NOK', flag: '🇳🇴' },
  { id: 'om', name_es: 'Omán', name_en: 'Oman', continent: 'Asia', currency: 'OMR', flag: '🇴🇲' },
  { id: 'pk', name_es: 'Pakistán', name_en: 'Pakistan', continent: 'Asia', currency: 'PKR', flag: '🇵🇰' },
  { id: 'pw', name_es: 'Palaos', name_en: 'Palau', continent: 'Oceania', currency: 'USD', flag: '🇵🇼' },
  { id: 'ps', name_es: 'Palestina', name_en: 'Palestine', continent: 'Asia', currency: 'ILS', flag: '🇵🇸' },
  { id: 'pa', name_es: 'Panamá', name_en: 'Panama', continent: 'North America', currency: 'PAB', flag: '🇵🇦' },
  { id: 'pg', name_es: 'Papúa Nueva Guinea', name_en: 'Papua New Guinea', continent: 'Oceania', currency: 'PGK', flag: '🇵🇬' },
  { id: 'py', name_es: 'Paraguay', name_en: 'Paraguay', continent: 'South America', currency: 'PYG', flag: '🇵🇾' },
  { id: 'pe', name_es: 'Perú', name_en: 'Peru', continent: 'South America', currency: 'PEN', flag: '🇵🇪' },
  { id: 'ph', name_es: 'Filipinas', name_en: 'Philippines', continent: 'Asia', currency: 'PHP', flag: '🇵🇭' },
  { id: 'pl', name_es: 'Polonia', name_en: 'Poland', continent: 'Europe', currency: 'PLN', flag: '🇵🇱' },
  { id: 'pt', name_es: 'Portugal', name_en: 'Portugal', continent: 'Europe', currency: 'EUR', flag: '🇵🇹' },
  { id: 'qa', name_es: 'Catar', name_en: 'Qatar', continent: 'Asia', currency: 'QAR', flag: '🇶🇦' },
  { id: 'ro', name_es: 'Rumania', name_en: 'Romania', continent: 'Europe', currency: 'RON', flag: '🇷🇴' },
  { id: 'ru', name_es: 'Rusia', name_en: 'Russia', continent: 'Europe', currency: 'RUB', flag: '🇷🇺' },
  { id: 'rw', name_es: 'Ruanda', name_en: 'Rwanda', continent: 'Africa', currency: 'RWF', flag: '🇷🇼' },
  { id: 'kn', name_es: 'San Cristóbal y Nieves', name_en: 'Saint Kitts and Nevis', continent: 'North America', currency: 'XCD', flag: '🇰🇳' },
  { id: 'lc', name_es: 'Santa Lucía', name_en: 'Saint Lucia', continent: 'North America', currency: 'XCD', flag: '🇱🇨' },
  { id: 'vc', name_es: 'San Vicente y las Granadinas', name_en: 'Saint Vincent and the Grenadines', continent: 'North America', currency: 'XCD', flag: '🇻🇨' },
  { id: 'ws', name_es: 'Samoa', name_en: 'Samoa', continent: 'Oceania', currency: 'WST', flag: '🇼🇸' },
  { id: 'sm', name_es: 'San Marino', name_en: 'San Marino', continent: 'Europe', currency: 'EUR', flag: '🇸🇲' },
  { id: 'st', name_es: 'Santo Tomé y Príncipe', name_en: 'Sao Tome and Principe', continent: 'Africa', currency: 'STN', flag: '🇸🇹' },
  { id: 'sa', name_es: 'Arabia Saudita', name_en: 'Saudi Arabia', continent: 'Asia', currency: 'SAR', flag: '🇸🇦' },
  { id: 'sn', name_es: 'Senegal', name_en: 'Senegal', continent: 'Africa', currency: 'XOF', flag: '🇸🇳' },
  { id: 'rs', name_es: 'Serbia', name_en: 'Serbia', continent: 'Europe', currency: 'RSD', flag: '🇷🇸' },
  { id: 'sc', name_es: 'Seychelles', name_en: 'Seychelles', continent: 'Africa', currency: 'SCR', flag: '🇸🇨' },
  { id: 'sl', name_es: 'Sierra Leona', name_en: 'Sierra Leone', continent: 'Africa', currency: 'SLL', flag: '🇸🇱' },
  { id: 'sg', name_es: 'Singapur', name_en: 'Singapore', continent: 'Asia', currency: 'SGD', flag: '🇸🇬' },
  { id: 'sk', name_es: 'Eslovaquia', name_en: 'Slovakia', continent: 'Europe', currency: 'EUR', flag: '🇸🇰' },
  { id: 'si', name_es: 'Eslovenia', name_en: 'Slovenia', continent: 'Europe', currency: 'EUR', flag: '🇸🇮' },
  { id: 'sb', name_es: 'Islas Salomón', name_en: 'Solomon Islands', continent: 'Oceania', currency: 'SBD', flag: '🇸🇧' },
  { id: 'so', name_es: 'Somalia', name_en: 'Somalia', continent: 'Africa', currency: 'SOS', flag: '🇸🇴' },
  { id: 'za', name_es: 'Sudáfrica', name_en: 'South Africa', continent: 'Africa', currency: 'ZAR', flag: '🇿🇦' },
  { id: 'ss', name_es: 'Sudán del Sur', name_en: 'South Sudan', continent: 'Africa', currency: 'SSP', flag: '🇸🇸' },
  { id: 'es', name_es: 'España', name_en: 'Spain', continent: 'Europe', currency: 'EUR', flag: '🇪🇸' },
  { id: 'lk', name_es: 'Sri Lanka', name_en: 'Sri Lanka', continent: 'Asia', currency: 'LKR', flag: '🇱🇰' },
  { id: 'sd', name_es: 'Sudán', name_en: 'Sudan', continent: 'Africa', currency: 'SDG', flag: '🇸🇩' },
  { id: 'sr', name_es: 'Surinam', name_en: 'Suriname', continent: 'South America', currency: 'SRD', flag: '🇸🇷' },
  { id: 'se', name_es: 'Suecia', name_en: 'Sweden', continent: 'Europe', currency: 'SEK', flag: '🇸🇪' },
  { id: 'ch', name_es: 'Suiza', name_en: 'Switzerland', continent: 'Europe', currency: 'CHF', flag: '🇨🇭' },
  { id: 'sy', name_es: 'Siria', name_en: 'Syria', continent: 'Asia', currency: 'SYP', flag: '🇸🇾' },
  { id: 'tw', name_es: 'Taiwán', name_en: 'Taiwan', continent: 'Asia', currency: 'TWD', flag: '🇹🇼' },
  { id: 'tj', name_es: 'Tayikistán', name_en: 'Tajikistan', continent: 'Asia', currency: 'TJS', flag: '🇹🇯' },
  { id: 'tz', name_es: 'Tanzania', name_en: 'Tanzania', continent: 'Africa', currency: 'TZS', flag: '🇹🇿' },
  { id: 'th', name_es: 'Tailandia', name_en: 'Thailand', continent: 'Asia', currency: 'THB', flag: '🇹🇭' },
  { id: 'tg', name_es: 'Togo', name_en: 'Togo', continent: 'Africa', currency: 'XOF', flag: '🇹🇬' },
  { id: 'to', name_es: 'Tonga', name_en: 'Tonga', continent: 'Oceania', currency: 'TOP', flag: '🇹🇴' },
  { id: 'tt', name_es: 'Trinidad y Tobago', name_en: 'Trinidad and Tobago', continent: 'North America', currency: 'TTD', flag: '🇹🇹' },
  { id: 'tn', name_es: 'Túnez', name_en: 'Tunisia', continent: 'Africa', currency: 'TND', flag: '🇹🇳' },
  { id: 'tr', name_es: 'Turquía', name_en: 'Turkey', continent: 'Europe', currency: 'TRY', flag: '🇹🇷' },
  { id: 'tm', name_es: 'Turkmenistán', name_en: 'Turkmenistan', continent: 'Asia', currency: 'TMT', flag: '🇹🇲' },
  { id: 'tv', name_es: 'Tuvalu', name_en: 'Tuvalu', continent: 'Oceania', currency: 'AUD', flag: '🇹🇻' },
  { id: 'ug', name_es: 'Uganda', name_en: 'Uganda', continent: 'Africa', currency: 'UGX', flag: '🇺🇬' },
  { id: 'ua', name_es: 'Ucrania', name_en: 'Ukraine', continent: 'Europe', currency: 'UAH', flag: '🇺🇦' },
  { id: 'ae', name_es: 'Emiratos Árabes Unidos', name_en: 'United Arab Emirates', continent: 'Asia', currency: 'AED', flag: '🇦🇪' },
  { id: 'gb', name_es: 'Reino Unido', name_en: 'United Kingdom', continent: 'Europe', currency: 'GBP', flag: '🇬🇧' },
  { id: 'us', name_es: 'Estados Unidos', name_en: 'United States', continent: 'North America', currency: 'USD', flag: '🇺🇸' },
  { id: 'uy', name_es: 'Uruguay', name_en: 'Uruguay', continent: 'South America', currency: 'UYU', flag: '🇺🇾' },
  { id: 'uz', name_es: 'Uzbekistán', name_en: 'Uzbekistan', continent: 'Asia', currency: 'UZS', flag: '🇺🇿' },
  { id: 'vu', name_es: 'Vanuatu', name_en: 'Vanuatu', continent: 'Oceania', currency: 'VUV', flag: '🇻🇺' },
  { id: 'va', name_es: 'Ciudad del Vaticano', name_en: 'Vatican City', continent: 'Europe', currency: 'EUR', flag: '🇻🇦' },
  { id: 've', name_es: 'Venezuela', name_en: 'Venezuela', continent: 'South America', currency: 'VES', flag: '🇻🇪' },
  { id: 'vn', name_es: 'Vietnam', name_en: 'Vietnam', continent: 'Asia', currency: 'VND', flag: '🇻🇳' },
  { id: 'ye', name_es: 'Yemen', name_en: 'Yemen', continent: 'Asia', currency: 'YER', flag: '🇾🇪' },
  { id: 'zm', name_es: 'Zambia', name_en: 'Zambia', continent: 'Africa', currency: 'ZMW', flag: '🇿🇲' },
  { id: 'zw', name_es: 'Zimbabue', name_en: 'Zimbabwe', continent: 'Africa', currency: 'ZWL', flag: '🇿🇼' },
];

export const INITIAL_OPERATORS: Operator[] = [
  { id: 'op_movistar', name: 'Movistar', country_id: 'es', technologies: ['4G', '5G'], website: 'movistar.es', coverage: '99%' },
  { id: 'op_vodafone', name: 'Vodafone', country_id: 'es', technologies: ['4G', '5G'], website: 'vodafone.es', coverage: '98%' },
  { id: 'op_docomo', name: 'NTT Docomo', country_id: 'jp', technologies: ['4G', '5G'], website: 'docomo.ne.jp', coverage: '99%' },
  { id: 'op_softbank', name: 'SoftBank', country_id: 'jp', technologies: ['4G', '5G'], website: 'softbank.jp', coverage: '97%' },
  { id: 'op_tmobile', name: 'T-Mobile', country_id: 'us', technologies: ['4G', '5G', '5G UC'], website: 't-mobile.com', coverage: '95%' },
];

export const INITIAL_PLANS: SimPlan[] = [
  { id: 'p1', operator_id: 'op_movistar', name: 'Prepago Total', data_gb: 140, price: 20, currency: 'EUR', validity_days: 28, sim_type: 'Hybrid', speed_5g: true, features: ['Roaming EU', 'Unlimited Calls'] },
  { id: 'p2', operator_id: 'op_vodafone', name: 'Vodafone Prepago L', data_gb: 100, price: 15, currency: 'EUR', validity_days: 28, sim_type: 'eSIM', speed_5g: true, features: ['Roaming UK/US', 'Chat Pass'] },
  { id: 'p3', operator_id: 'op_docomo', name: 'Tourist Plan', data_gb: 3, price: 2000, currency: 'JPY', validity_days: 15, sim_type: 'eSIM', speed_5g: false, features: ['Data Only'] },
  { id: 'p4', operator_id: 'op_tmobile', name: 'Connect Unlimited', data_gb: -1, price: 50, currency: 'USD', validity_days: 30, sim_type: 'eSIM', speed_5g: true, features: ['Hotspot 5GB'] },
];

export const MOCK_USER: User = {
  name: 'Alex Traveler',
  points: 320,
  level: 'Expert',
  badges: ['Explorador Mundial', 'Cazador de Ofertas'],
  contributions: 45
};

export const TRANSLATIONS = {
  en: {
    title: 'Global SIM Connect Ultimate',
    subtitle: 'Collaborative Worldwide Mobile Operator Database',
    searchPlaceholder: 'Search for a country...',
    home: 'Home',
    dashboard: 'Dashboard',
    contribute: 'Contribute',
    compare: 'Compare',
    aiAdvisor: 'AI Voice Advisor',
    calculator: 'Trip Calculator',
    popularCountries: 'Popular Countries',
    operators: 'Operators',
    plans: 'SIM Plans',
    price: 'Price',
    data: 'Data',
    validity: 'Validity',
    speed: 'Speed',
    type: 'Type',
    addEntry: 'Add New Entry',
    addToCompare: 'Add to Compare',
    bestValue: 'Best Value',
    userLevel: 'User Level',
    badges: 'Badges',
    submit: 'Submit Contribution',
    aiPrompt: 'Where are you traveling and what are your needs?',
    loading: 'Loading...',
    askAi: 'Ask AI Assistant',
  },
  es: {
    title: 'Global SIM Connect Ultimate',
    subtitle: 'Base de Datos Colaborativa Mundial de Operadores Móviles',
    searchPlaceholder: 'Busca un país...',
    home: 'Inicio',
    dashboard: 'Perfil',
    contribute: 'Contribuir',
    compare: 'Comparar',
    aiAdvisor: 'Asesor Voz IA',
    calculator: 'Calculadora Viaje',
    popularCountries: 'Países Populares',
    operators: 'Operadores',
    plans: 'Planes SIM',
    price: 'Precio',
    data: 'Datos',
    validity: 'Validez',
    speed: 'Velocidad',
    type: 'Tipo',
    addEntry: 'Añadir Entrada',
    addToCompare: 'Comparar',
    bestValue: 'Mejor Precio',
    userLevel: 'Nivel de Usuario',
    badges: 'Insignias',
    submit: 'Enviar Contribución',
    aiPrompt: '¿A dónde viajas y qué necesitas?',
    loading: 'Cargando...',
    askAi: 'Preguntar a la IA',
  }
};